firstDOW: 1,
labelDayOfMonth: 'Jour du mois',
labelDismiss: 'X',
labelHour: 'Heure',
labelMinute: 'Minute',
labelMonth: 'Mois',
labelTimeZone: 'Fuseau horaire',
labelSecond: 'Secondes',
labelTitle: 'Choisissez votre date',
labelYear: 'Année',
dayAbbreviations: ['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'],
dayNames: ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
monthAbbreviations: ['Jan','Fév','Mar','Avr','Mai','Juin','Juil','Aoû','Sep','Oct','Nov','Déc'],
monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre']
